### ISSUE TITLE
"less secure app" message by Google

### ISSUE THREAD

**Issue by martijnvv** [kbroman/mygmailR#1]
I received an warning mail from Google about a less secure app. It suggests an update from this functionality to a more current version of security.
<img width="493" alt="knipsel" src="https://cloud.githubusercontent.com/assets/7570291/17968089/381ae644-6acb-11e6-87ae-535cd37d465e.PNG">

Changing the setting does work.

**Comment by kbroman** [comment]
This seems more like an issue for the [gmailR](https://github.com/trinker/gmailR) package than for the present one, which just includes a device for handling the private information (and in a way that is, admittedly, not at all secure).

Personally, I'm not using this package anymore, but rather using [RPushbullet](https://cran.r-project.org/web/packages/RPushbullet/) to send myself messages from R.
